// Table eveworld.AccessEnforcePer {
//   smartObjectId uint256
//   target bytes32
//   isEnforced bool
// }
// 
// Table eveworld.AccessEnforcemen {
//   target bytes32
//   isEnforced bool
// }
// 
// Table eveworld.AccessRole {
//   roleId bytes32
//   accounts address[]
// }
// 
// Table eveworld.AccessRolePerObj {
//   smartObjectId uint256
//   roleId bytes32
//   accounts address[]
// }
// 
// Table eveworld.AccessRolePerSys {
//   systemId bytes32
//   roleId bytes32
//   accounts address[]
// }

Table eveworld.CharactersByAddr {
  characterAddress address
  characterId uint256
}

// Table eveworld.CharactersConsta {
//   erc721Address address
// }
 
Table eveworld.CharactersTable {
  characterId uint256
  characterAddress address
  corpId uint256
  createdAt uint256
}

// Table eveworld.ClassConfig {
//   systemId bytes32
//   classId uint256
// }

Table eveworld.DeployableFuelBa {
  smartObjectId uint256
  fuelUnitVolume uint256
  fuelConsumptionPerMinute uint256
  fuelMaxCapacity uint256
  fuelAmount uint256
  lastUpdatedAt uint256
}

Table eveworld.DeployableState {
  smartObjectId uint256
  createdAt uint256
  previousState uint8
  currentState uint8
  isValid bool
  anchoredAt uint256
  updatedBlockNumber uint256
  updatedBlockTime uint256
}

// Table eveworld.DeployableTokenT {
//   erc721Address address
// }
// 
// Table eveworld.EntityAssociatio {
//   entityId uint256
//   moduleIds uint256[]
//   hookIds uint256[]
// }

Table eveworld.EntityMap {
  entityId uint256
  taggedEntityIds uint256[]
}

Table eveworld.EntityRecordOffc {
  entityId uint256
  name string
  dappURL string
  description string
}

Table eveworld.EntityRecordTabl {
  entityId uint256
  itemId uint256
  typeId uint256
  volume uint256
  recordExists bool
}
 
Table eveworld.EntityTable {
  entityId uint256
  doesExists bool
  entityType uint8
}

Table eveworld.EntityType {
  typeId uint8
  doesExists bool
  typeName bytes32
}

// Table eveworld.EntityTypeAssoci {
//   entityType uint8
//   taggedEntityType uint8
//   isAllowed bool
// }
// 
// Table eveworld.EphemeralInvCapa {
//   smartObjectId uint256
//   capacity uint256
// }
// 
// Table eveworld.EphemeralInvItem {
//   smartObjectId uint256
//   inventoryItemId uint256
//   ephemeralInvOwner address
//   quantity uint256
//   index uint256
//   stateUpdate uint256
// }
// 
// Table eveworld.EphemeralInvTabl {
//   smartObjectId uint256
//   ephemeralInvOwner address
//   usedCapacity uint256
//   items uint256[]
// }
// 
// Table eveworld.GlobalDeployable {
//   updatedBlockNumber uint256
//   isPaused bool
//   lastGlobalOffline uint256
//   lastGlobalOnline uint256
// }
// 
// Table eveworld.GlobalStaticData {
//   trustedForwarder address
//   value bool
// }
// 
// Table eveworld.HookTable {
//   hookId uint256
//   isHook bool
//   systemId bytes32
//   functionSelector bytes4
// }
// 
// Table eveworld.HookTargetAfter {
//   hookId uint256
//   targetId uint256
//   hasHook bool
//   systemSelector bytes32
//   functionSelector bytes4
// }
// 
// Table eveworld.HookTargetBefore {
//   hookId uint256
//   targetId uint256
//   hasHook bool
//   systemSelector bytes32
//   functionSelector bytes4
// }
// 
// Table eveworld.InventoryItemTab {
//   smartObjectId uint256
//   inventoryItemId uint256
//   quantity uint256
//   index uint256
//   stateUpdate uint256
// }
// 
// Table eveworld.InventoryTable {
//   smartObjectId uint256
//   capacity uint256
//   usedCapacity uint256
//   items uint256[]
// }
// 
// Table eveworld.ItemTransferOffc {
//   smartObjectId uint256
//   inventoryItemId uint256
//   previousOwner address
//   currentOwner address
//   quantity uint256
//   updatedAt uint256
// }

Table eveworld.KillMailTable {
  killMailId uint256
  killerCharacterId uint256
  victimCharacterId uint256
  lossType uint8
  solarSystemId uint256
  killTimestamp uint256
}

Table eveworld.LocationTable {
  smartObjectId uint256
  solarSystemId uint256
  x uint256
  y uint256
  z uint256
}

// Table eveworld.ModuleSystemLook {
//   moduleId uint256
//   systemIds bytes32[]
// }
// 
// Table eveworld.ModuleTable {
//   moduleId uint256
//   systemId bytes32
//   moduleName bytes16
//   doesExists bool
// }
// 
// Table eveworld.Role {
//   role bytes32
//   value address
// }

Table eveworld.SmartAssemblyTab {
  smartObjectId uint256
  smartAssemblyType uint8
}

// Table eveworld.SmartGateConfigT {
//   smartObjectId uint256
//   systemId bytes32
//   maxDistance uint256
// }
// 
// Table eveworld.SmartGateLinkTab {
//   sourceGateId uint256
//   destinationGateId uint256
//   isLinked bool
// }
// 
// Table eveworld.SmartTurretConfi {
//   smartObjectId uint256
//   systemId bytes32
// }
// 
// Table eveworld.StaticDataGlobal {
//   systemId bytes32
//   name string
//   symbol string
//   baseURI string
// }
// 
// Table eveworld.StaticDataTable {
//   entityId uint256
//   cid string
// }
// 



Ref: "eveworld"."CharactersByAddr"."characterAddress" - "eveworld"."CharactersTable"."characterAddress"

Ref: "eveworld"."CharactersByAddr"."characterId" - "eveworld"."CharactersTable"."characterId"

Ref: "eveworld"."CharactersTable"."characterId" - "eveworld"."EntityRecordOffc"."entityId"

Ref: "eveworld"."EntityRecordOffc"."entityId" - "eveworld"."EntityMap"."entityId"

Ref: "eveworld"."EntityRecordTabl"."entityId" - "eveworld"."EntityRecordOffc"."entityId"

Ref: "eveworld"."EntityTable"."entityId" - "eveworld"."EntityRecordOffc"."entityId"

Ref: "eveworld"."EntityTable"."entityType" - "eveworld"."EntityType"."typeId"

Ref: "eveworld"."DeployableState"."smartObjectId" < "eveworld"."EntityRecordOffc"."entityId"

Ref: "eveworld"."DeployableState"."smartObjectId" - "eveworld"."SmartAssemblyTab"."smartObjectId"

Ref: "eveworld"."DeployableState"."smartObjectId" - "eveworld"."EntityRecordTabl"."entityId"

Ref: "eveworld"."DeployableState"."smartObjectId" < "eveworld"."EntityTable"."entityId"

Ref: "eveworld"."DeployableState"."smartObjectId" - "eveworld"."LocationTable"."smartObjectId"

Ref: "eveworld"."KillMailTable"."killerCharacterId" - "eveworld"."CharactersTable"."characterId"

Ref: "eveworld"."KillMailTable"."victimCharacterId" - "eveworld"."CharactersTable"."characterId"

Ref: "eveworld"."DeployableState"."smartObjectId" - "eveworld"."DeployableFuelBa"."smartObjectId"