/* 
Table evefrontier.AccessConfig {
  target bytes32
  configured bool
  targetSystemId bytes32
  targetFunctionId bytes4
  accessSystemId bytes32
  accessFunctionId bytes4
  enforcement bool
}
*/
Table evefrontier.AssemblyEnergyCo {
  assemblyTypeId uint256 [ref: > evefrontier.SmartAssembly.assemblyType, not null]
  energyConstant uint256
}
/*
Table evefrontier.CallAccess {
  systemId bytes32
  functionId bytes4
  caller address
  hasAccess bool
} 
*/

Table evefrontier.Characters {
  smartObjectId uint256 [not null]
  exists bool
  tribeId uint256
  createdAt uint256
}

Ref: evefrontier.Characters.smartObjectId - evefrontier.EntityRecordMeta.smartObjectId
Ref: evefrontier.Characters.smartObjectId - evefrontier.CharactersByAcco.smartObjectId
Ref: evefrontier.Characters.smartObjectId > evefrontier.KillMail.killerCharacterId
Ref: evefrontier.Characters.smartObjectId > evefrontier.KillMail.victimCharacterId

Table evefrontier.CharactersByAcco {
  account address [not null]
  smartObjectId uint256 [not null]
}


Table evefrontier.DeployableState {
  smartObjectId uint256  [not null]
  createdAt uint256
  previousState uint8
  currentState uint8
  isValid bool
  anchoredAt uint256
  updatedBlockNumber uint256
  updatedBlockTime uint256
}

/*
Table evefrontier.Entity {
  entityId uint256
  exists bool
  accessRole bytes32
  entityRelationTag bytes32
  propertyTags bytes32[]
  resourceRelationTags bytes32[]
}
*/
/*
Table evefrontier.EntityRecord {
  smartObjectId uint256
  exists bool
  tenantId bytes32
  typeId uint256
  itemId uint256
  volume uint256
}
*/
Table evefrontier.EntityRecordMeta {
  smartObjectId uint256
  name string
  dappURL string
  description string
}

/*
Table evefrontier.EntityTagMap {
  entityId uint256
  tagId bytes32
  hasTag bool
  tagIndex uint256
  value bytes
}
*/
Table evefrontier.EphemeralInvCapa {
  smartObjectId uint256
  capacity uint256
}

Table evefrontier.EphemeralInvItem {
  smartObjectId uint256
  ephemeralOwner address [ref: < evefrontier.CharactersByAcco.account]
  itemObjectId uint256
  exists bool
  quantity uint256
  index uint256
  version uint256
}

Table evefrontier.EphemeralInvento {
  smartObjectId uint256
  ephemeralOwner address [ref: < evefrontier.CharactersByAcco.account]
  capacity uint256
  usedCapacity uint256
  version uint256
  items uint256[]
}

/*
Table evefrontier.EphemeralItemTra {
  smartObjectId uint256
  itemObjectId uint256
  previousOwner address
  currentOwner address
  quantity uint256
  updatedAt uint256
}
*/
Table evefrontier.Fuel {
  smartObjectId uint256
  fuelSmartObjectId uint256
  fuelMaxCapacity uint256
  fuelAmount uint256
  fuelBurnRateInSeconds uint256
  lastUpdatedAt uint256
}

Table evefrontier.FuelConsumptionS {
  smartObjectId uint256 [ref: - evefrontier.Fuel.smartObjectId]
  burnStartTime uint256
  burnState bool
  fuelConsumptionTimeRemaining uint256
}

Table evefrontier.FuelEfficiencyCo {
  smartObjectId uint256  [ref: - evefrontier.Fuel.fuelSmartObjectId]
  efficiency uint256
}

/*
Table evefrontier.GlobalStaticData {
  trustedForwarder address
  value bool
}

Table evefrontier.HasRole {
  role bytes32
  account address
  isMember bool
  index uint256
}

Table evefrontier.Initialize {
  systemId bytes32
  classId uint256
}

Table evefrontier.Initialized {
  systemId bytes32
  initialized bool
}
*/
Table evefrontier.Inventory {
  smartObjectId uint256
  capacity uint256
  usedCapacity uint256
  version uint256
  items uint256[]
}
/*
Table evefrontier.InventoryByEphem {
  ephemeralSmartObjectId uint256
  exists bool
  smartObjectId uint256
  ephemeralOwner address
}

Table evefrontier.InventoryByItem {
  itemObjectId uint256
  inventoryObjectId uint256
}
*/
Table evefrontier.InventoryItem {
  smartObjectId uint256
  itemObjectId uint256
  exists bool
  quantity uint256
  index uint256
  version uint256
}
/*
Table evefrontier.InventoryItemTra {
  smartObjectId uint256
  itemObjectId uint256
  toObjectId uint256
  previousOwner address
  currentOwner address
  quantity uint256
  updatedAt uint256
}
*/

Table evefrontier.KillMail {
  killMailId uint256
  killerCharacterId uint256
  victimCharacterId uint256
  lossType uint8
  solarSystemId uint256
  killTimestamp uint256
}

Table evefrontier.Location {
  smartObjectId uint256
  solarSystemId uint256
  x uint256
  y uint256
  z uint256
}


Table evefrontier.NetworkNode {
  smartObjectId uint256 [not null]
  exists bool
  maxEnergyCapacity uint256
  energyProduced uint256
  totalReservedEnergy uint256
  lastUpdatedAt uint256
  connectedAssemblies uint256[]
}

Table evefrontier.NetworkNodeAssem {
  networkNodeId uint256 [ref: < evefrontier.NetworkNode.smartObjectId]
  assemblyId uint256
  isConnected bool
  connectedAt uint256
}

Table evefrontier.NetworkNodeByAss {
  assemblyId uint256 
  networkNodeId uint256 [ref: < evefrontier.NetworkNode.smartObjectId]
}

Table evefrontier.NetworkNodeEnerg {
  networkNodeId uint256  [ref: < evefrontier.NetworkNode.smartObjectId]
  timestamp uint256
  totalReservedEnergy uint256
}

Table evefrontier.OwnershipByObjec {
  smartObjectId uint256 [not null]
  account address
}

Ref: evefrontier.Characters.smartObjectId - evefrontier.OwnershipByObjec.smartObjectId

/*
Table evefrontier.Role {
  role bytes32
  exists bool
  admin bytes32
  members address[]
}
*/


Table evefrontier.SmartAssembly {
  smartObjectId uint256 
  assemblyType string
}

Ref: evefrontier.SmartAssembly.smartObjectId - evefrontier.OwnershipByObjec.smartObjectId
Ref: evefrontier.SmartAssembly.smartObjectId - evefrontier.DeployableState.smartObjectId
Ref: evefrontier.SmartAssembly.smartObjectId - evefrontier.Location.smartObjectId
Ref: evefrontier.SmartAssembly.smartObjectId - evefrontier.EntityRecordMeta.smartObjectId
Ref: evefrontier.SmartAssembly.smartObjectId - evefrontier.SmartGateConfig.smartObjectId
Ref: evefrontier.SmartAssembly.smartObjectId - evefrontier.SmartTurretConfi.smartObjectId
Ref: evefrontier.SmartAssembly.smartObjectId - evefrontier.SmartGateLink.sourceGateId
Ref: evefrontier.SmartAssembly.smartObjectId - evefrontier.SmartGateLink.destinationGateId
Ref: evefrontier.SmartAssembly.smartObjectId - evefrontier.EphemeralInvCapa.smartObjectId
Ref: evefrontier.SmartAssembly.smartObjectId - evefrontier.EphemeralInvento.smartObjectId
Ref: evefrontier.SmartAssembly.smartObjectId - evefrontier.EphemeralInvItem.smartObjectId
Ref: evefrontier.SmartAssembly.smartObjectId - evefrontier.Inventory.smartObjectId
Ref: evefrontier.SmartAssembly.smartObjectId - evefrontier.InventoryItem.smartObjectId
Ref: evefrontier.SmartAssembly.smartObjectId - evefrontier.Fuel.smartObjectId
Ref: evefrontier.SmartAssembly.smartObjectId - evefrontier.NetworkNode.smartObjectId
Ref: evefrontier.SmartAssembly.smartObjectId - evefrontier.NetworkNodeAssem.assemblyId
Ref: evefrontier.SmartAssembly.smartObjectId - evefrontier.NetworkNodeByAss.assemblyId


Table evefrontier.SmartGateConfig {
  smartObjectId uint256
  systemId bytes32
  maxDistance uint256
}

Table evefrontier.SmartGateLink {
  sourceGateId uint256
  destinationGateId uint256
  isLinked bool
}

Table evefrontier.SmartTurretConfi {
  smartObjectId uint256
  systemId bytes32
}

/*
Table evefrontier.Tenant {
  tenantId bytes32
}
 */
